from __future__ import annotations

import random

from tfwr import farm
from tfwr.common import *

WALL = 1
PATH = 0


def spawn_maze(farm: farm.Farm, substance: int) -> None:
    cost = farm.get_cost(Entities.Treasure, False)
    assert cost is not None
    cost = cost[Items.Weird_Substance]
    size = substance // cost
    bottom_left = _find_bottom_left_maze(farm, size)
    goal = (random.randint(0, size - 1), random.randint(0, size - 1))
    next_goal = (random.randint(0, size - 1), random.randint(0, size - 1))
    walls, possible_walls = _generate_maze(size, goal)
    real_goal_coords = (goal[0] + bottom_left[0], goal[1] + bottom_left[1])
    real_next_coords = (next_goal[0] + bottom_left[0], next_goal[1] + bottom_left[1])
    farm.data["treasure coords"] = real_goal_coords
    farm.data["next treasure coords"] = real_next_coords
    farm.data["times reused"] = 0
    farm.data["walls"] = walls
    farm.data["possible walls"] = possible_walls
    farm.data["maze tiles"] = _get_tile_coords(size, bottom_left)
    farm.data["maze size"] = size
    farm.data["wall remove counter"] = 0
    for coords in farm.data["maze tiles"]:
        tile = farm.get_tile(*coords)
        tile.clear()
        if coords == real_goal_coords:
            tile.plant(Entities.Treasure)
        else:
            tile.plant(Entities.Hedge)


def reuse_maze(f: farm.Farm) -> None:
    _remove_walls(f)
    f.data["times reused"] += 1
    new_coords = f.data["next treasure coords"]
    next_coords = random.choice(f.data["maze tiles"])
    while next_coords == new_coords:
        next_coords = random.choice(f.data["maze tiles"])
    f.data["treasure coords"] = new_coords
    f.data["next treasure coords"] = next_coords
    f.current_tile.plant(Entities.Hedge)
    f.get_tile(*new_coords).plant(Entities.Treasure)


def _remove_walls(f: farm.Farm) -> None:
    remove_ct = _get_num_walls_to_remove(f)
    for i in range(remove_ct):
        f.data["walls"].pop()


def _get_num_walls_to_remove(f: farm.Farm) -> int:
    """
    Compute a semi-randomized "percent of remaining walls" to remove then
    remove that many.

    The range of the randomization is based slightly on the size of the maze
    and is just extrapolated from data. An average of 0.18% of walls are
    removed each iteration, with randomness around this. For small mazes
    especially this may not result in any wall removals at all. So if no walls
    are removed, the calculated fractional number of walls to be removed is
    added to a counter. When this counter reaches 1, an additional wall is
    removed and the counter resets to 0.

    Note that this is definitely NOT how the game's wall removal works. In the
    game, it is possible for at least 8 walls to be removed at once in a 32x32
    sized maze and a good number of iterations will remove 0. For this method,
    however, a 32x32 will instead have a regular removal of 1-3 walls most of
    the time. See the bottom of this file for some probably incorrect ideas on
    how the game might remove walls.
    """
    # magic constants estimated from some test data
    range_mult = 5.65 + 0.04 * f.data["maze size"]
    half_range = range_mult / (f.data["maze size"] * 2)
    # another magic constant from test data
    pct_remaining_remove = random.uniform(0.18 - half_range, 0.18 + half_range)
    to_remove = pct_remaining_remove * len(f.data["walls"]) / 100
    ret = round(to_remove)
    f.data["wall remove counter"] += to_remove - ret if ret < 1 else 0
    if f.data["wall remove counter"] >= 1:
        ret += 1
        f.data["wall remove counter"] = 0
    return ret


# generated by Gemini
def _generate_maze_array(size: int, goal: Coords) -> list[list[int]]:
    size = 2 * size + 1
    maze = [[WALL for _ in range(size)] for _ in range(size)]

    # Recursive backtracker function
    def carve_paths(cx: int, cy: int):
        maze[cy][cx] = 0  # Mark current cell as path
        directions = [(0, -2), (0, 2), (-2, 0), (2, 0)]
        random.shuffle(directions)
        for dx, dy in directions:
            nx, ny = cx + dx, cy + dy
            if 0 < nx < size and 0 < ny < size and maze[ny][nx] == 1:
                maze[cy + dy // 2][cx + dx // 2] = PATH
                carve_paths(nx, ny)

    carve_paths(*goal)
    return maze


# translation layer from the array maze to what the farm needs
def _generate_maze(size: int, goal: Coords) -> tuple[set[Coords], set[Coords]]:
    goal = (2 * goal[0] + 1, 2 * goal[1] + 1)
    maze_array = _generate_maze_array(size, goal)
    walls = set()
    all_edges = set()
    for i in range(size):
        row_idx = 2 * i + 1
        for j in range(size):
            col_idx = 2 * j + 1
            pos = (i, j)
            _add_edges(maze_array, walls, all_edges, pos, row_idx, col_idx)
    return walls, all_edges


def _add_edges(
    arr: list[list[int]],
    paths: set[tuple[Coords, Coords]],
    all_edges: set[tuple[Coords, Coords]],
    pos: Coords,
    row_idx: int,
    col_idx: int,
) -> None:
    x, y = pos
    conditions = [x > 0, x < len(arr) - 1, y < len(arr) - 1, y > 0]
    dir_diff = [(-1, 0), (1, 0), (0, 1), (0, -1)]
    for i in range(len(dir_diff)):
        cmp_row = row_idx + dir_diff[i][0]
        cmp_col = col_idx + dir_diff[i][1]
        is_wall = arr[cmp_row][cmp_col] == WALL
        if conditions[i]:
            neighbor = (x + dir_diff[i][0], y + dir_diff[i][1])
            e1, e2 = (pos, neighbor), (neighbor, pos)
            if e1 not in all_edges and e2 not in all_edges:
                all_edges.add(e1)
                if is_wall:
                    paths.add(e1)


def _get_tile_coords(size: int, bottom_left: Coords) -> list[Coords]:
    coords = []
    for x in range(size):
        for y in range(size):
            coords.append((x + bottom_left[0], y + bottom_left[1]))
    return coords


def _find_bottom_left_maze(farm, size: int) -> Coords:
    x = farm.x
    y = farm.y
    top_x = x + size // 2
    top_y = y + size // 2
    # If the maze size is even, it spawns with the drone in the top right
    # of the center four squares. Otherwise it spawns with the drone in
    # the center.
    if size % 2 == 0:
        # Account for drone top right offset by moving the top coordinates
        # for the purposes of fitting the maze on the farm and the center
        # coordinates to account for the fact that down and left is 1 tile
        # further than size // 2
        top_x -= 1
        top_y -= 1
    # Represents how much each coordinate needs to adjust if the maze would
    # otherwise go off the farm up/right.
    x_adjustment = max(0, top_x - (farm.farm_x - 1))
    y_adjustment = max(0, top_y - (farm.farm_y - 1))
    x = max(0, x - size // 2 - x_adjustment)
    y = max(0, y - size // 2 - y_adjustment)
    return (x, y)
